version: '3.8'

services:
  bot:
    container_name: bot
    build: .
  db:
    container_name: db
    ports:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user_tg
    image: postgres:alpine3.17


